[build]
  publish = "/"

# Nastavení HTTPS a HTTP hlaviček
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com https://docs.google.com; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data:;"

# Přesměrování HTTP na HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Zajistí, že cesty jako /majak správně zobrazí majak.html
[[redirects]]
  from = "/majak"
  to = "/majak.html"
  status = 200
  
[[redirects]]
  from = "/calculator"
  to = "/calculator.html"
  status = 200
  
[[redirects]]
  from = "/members"
  to = "/members.html"
  status = 200
  
[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

# Fallback - pro SPA aplikace
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 